name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ["3.9", "3.10", "3.11", "3.12"]

    name: ${{ matrix.platform }} / Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
      - name: Setup node
        uses: actions/setup-node@v4
        with:
            node-version: 18
      - name: Build frontend
        run: |
          cd ./frontend
          npm install
          npm run build
      - name: Install dependencies
        run: npm cache verify && npm ci
      - name: Test packages
        run: npm test --if-present || exit 0

  build_test_all:
    if: always()
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Check build matrix status
        if: ${{ needs.build_test.result != 'success' }}
        run: exit 1